### ISSUE TITLE
Cards with same name whitelisted [bug]

### ISSUE THREAD

**Issue by Milkamilk** [IasonNautica/betterPackOpener#1]
Cards with the same name are whitelisted, despite them being from alternate formats (Rush/Anime). Cards that are always treated as the same name (Umi and Legendary Ocean, Pacifis, the Phantasm City, etc...) are also whitelisted if one of them is legal. The picture attached shows different Umis being legal, despite the whitelist being created only from pulls from Legend of Blue-Eyes White Dragon.
![UmiWhitelist](https://user-images.githubusercontent.com/91711702/135560777-8b4dffb1-538f-4c2a-b9e8-327a6994bc30.PNG)

I limited Umi to be more clear but the point is that changing the legality of one whitelists all the others. Here is another example with sparks.
![SparksRushWhitelist](https://user-images.githubusercontent.com/91711702/135560922-c528177d-a810-4a42-aabb-91ae36c208bd.PNG)

Here is my lflist file as a .txt file:
[lflisttext.txt](https://github.com/IasonNautica/betterPackOpener/files/7263952/lflisttext.txt)

**Comment by IasonNautica** [comment]
Hey, thanks for the heads up, I completely forgot about this issue.
The umi clones and harpie lady cards should hopefully work correctly now. Edopro just requires you to blacklist the individual cards you don't have
As for the rush and anime cards, it's a bit more of a headache since I can't find any comprehensive list of anime/rush cards in edopro (and it's impossible to tell whether a card has a rush alias or not before adding it in)
What I've done is that I copied off the rush and anime card blacklist from Reaper format. It's not all of them, but should be MOST of the cards that have real game counterparts.

I'll leave this open while we don't have a way to scrub all of them though. (If someone could be a lad and put ALL anime and rush cards with TCG counterparts in a .ydk, that'd help)

**Comment by IasonNautica** [comment]
I finally found a repository with all the anime cards. This should be fixed for all following generated banlists
